### ISSUE TITLE
Running tools through pre-commit

### ISSUE THREAD

**Issue by eavanvalkenburg** [astral-sh/uv-pre-commit#14]
I would like the ability to use `uv tool run ruff` with this! Especially ruff and mypy!

**Comment by UnknownPlatypus** [comment]
I don't understand the point of running `uv tool` via `pre-commit`. This seems like adding layers upon layers of indirection.

`pre-commit` is already a tool designed to install hook in isolated environment, similarly to what `uv tool` does.

Adding the feature you ask for would mean that pre-commit will create a venv inside which uv is installed to create a venv to install the tool you ask for. Maybe you are looking for https://github.com/tox-dev/pre-commit-uv, this project uses uv to handle the python venv creation inside pre-commit.

For ruff, I would recommended the supported [pre-commit hook](https://github.com/astral-sh/ruff-pre-commit):
```yaml
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
```
For mypy there is https://github.com/pre-commit/mirrors-mypy (but mypy is slow, pre-commit is maybe not the right place to run it)

**Comment by CarliJoy** [comment]
I also would be in favour of running `mypy` through this pre-commit hook. But not with `uv tool run` but `uv run`.

Why not  https://github.com/pre-commit/mirrors-mypy  ?
Because it doesn't create the environment. I would have to add all dependencies manually to the pre-commit hook.
Using `uv run mypy` everything is properly installed using the `pyproject.toml` configuration.

Indeed it would be nice if `pre-commit` would support creating a hook that contains the current project installed in develop mode but it doesn't. So it might be an idea to ask for [PEP 735](https://peps.python.org/pep-0735/) support in pre-commit in order to use a `dependency-groups` as [`additional_dependencies`](https://pre-commit.com/#config-additional_dependencies).

But this way the env `pre-commit` caches would not update if the lock file updates.
Using `uv run mypy` ensures all used environments are using the same version.

I am currently helped myself with:

```yaml
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        args: []
        language: system
        types: [python]
```

Which requires `uv` to be installed in `$PATH`.

Having it here this requirement would vanish.

**Comment by danielhollas** [comment]
I've opened WIP branch on my fork for the `uv-run` hook, PR at #42.

@CarliJoy would you mind giving it a go? I am interested if it works for your mypy use case. Something like this in the `.pre-commit-config.yaml` should work

```yaml
repos:   
  - repo: https://github.com/danielhollas/uv-pre-commit
    rev: c2c5e6a1c7d17dd3c237aae6557d15a142b89b8c
    hooks:
   - id: uv-run    
      name: mypy type check    
      args: [mypy]    
      pass_filenames: true    
      types: [python]          
```

There are two disadvantages to this approach:
1. It won't work on `pre-commit.ci` service since it needs network access, which is forbidden during hook execution on `pre-commit.ci`.
2. If you want to execute a single hook, you will need to refer to if via the `uv-run` hook id which might be non-obvious e.g.

```console
$ pre-commit run uv-run --all-files
```

This would get awkward once you'd want to run multiple things via `uv run`, you can still define multiple hooks with the same id, but you wouldn't be able to refer to them via a unique name.

**Comment by Jamie-BitFlight** [comment]
Following up on @CarliJoy's mypy use case - I built a tool that handles this exact scenario, especially when you have PEP 723 inline script dependencies that need to be installed before linting.

`pep723-loader` wraps any linter and auto-installs PEP 723 dependencies first:

```yaml
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: uv run -q --no-sync --with pep723-loader --with mypy pep723-loader mypy
      language: system
      types: [python]
      pass_filenames: true
```

It works by:
1. Scanning passed Python files for `# /// script` metadata blocks
2. Running `uv export --script` to extract dependencies
3. Installing them via `uv pip install`
4. Executing the wrapped linter with original args

This avoids the `additional_dependencies` maintenance burden in mirrors-mypy, and handles scripts that declare their own inline dependencies.

PyPI: `pip install pep723-loader`
Repo: https://github.com/Jamie-BitFlight/pre-commit-pep723-linter-wrapper
