### ISSUE TITLE
uv lock for pyproject in subfolder

### ISSUE THREAD

**Issue by eavanvalkenburg** [astral-sh/uv-pre-commit#15]
I'm working in a mono-repo and have the pyproject.toml sitting in a subfolder, is there a way to specify this for the uv-lock hook?

**Comment by spwoodcock** [comment]
You can do this:

```yaml
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.2
    hooks:
      - id: uv-lock
        files: path/to/project/pyproject.toml
        args: [--project, path/to/project]
```

**Comment by daturkel** [comment]
This might be worth putting in the readme!

**Comment by kshpytsya** [comment]
I have encountered this issue trying to employ this for a git repo containing multiple subdirectories containing `pyproject.toml`/`uv.lock` pairs I need to check for being in sync.

**Comment by NodeJSmith** [comment]
@seh-dev In case it helps, I created a local hook to do the same thing

saved as `uv_pip_compile.sh`
```bash
#!/usr/bin/env bash

if uv --version &>/dev/null; then
    echo "uv is installed"
else
    echo "uv is not installed. Please install it using 'pip install uv'"
    exit 1
fi

for f in "$@"; do
    echo "Compiling $f"
    output_dir=$(dirname "$f")
    output_file=requirements.txt

    full_output_path=$output_dir/$output_file
    echo "Output file: $full_output_path"

    if uv pip compile --generate-hashes --output-file "$full_output_path" "$f"; then
        echo "Compiled $f to $full_output_path"
    else
        echo "Failed to compile $f"
        exit 1
    fi
done
```

```yaml
  - repo: local
    hooks:
      - id: uv-pip-compile
        name: uv-pip-compile
        entry: ./uv_pip_compile.sh
        language: system
        files: pyproject.toml
        stages: ["pre-push", "manual"]
```
