### ISSUE TITLE
Post-merge hook for lockfile sync

### ISSUE THREAD

**Issue by nathanjmcdougall** [astral-sh/uv-pre-commit#17]
One workflow that could be quite nice is to automatically run `uv sync` post-merge if there are any incoming changes to the lock file. That way, everyone's development environments can stay synchronized automatically.

**Comment by zanieb** [comment]
I think `uv lock` should suffice for pre-commit as added in #13. What benefit is there to doing `uv sync`? The virtual environment should not be committed.

**Comment by nathanjmcdougall** [comment]
Definitely don't want to be committing the virtual environment.

If you are working on a codebase with a frequently changing lockfile, then often the `main` branch will be merged back into a dev branch, updating the lockfile, but rendering your environment out of date. Yes, the lockfile might automatically get updated every commit on the dev branch with `uv lock`, but this doesn't do anything to ensure your environment is up-to-date.

One way to deal with this is to display a warning when the lockfile is out-of-sync with the current environment, but if it's happening frequently, users might just want to automatically run `uv sync` after any merge rather than having to remember to do it themselves. It might also make it easier to deal with merge conflicts in the lockfile (?).

**Comment by lachaib** [comment]
This is exactly what I was looking for 😄 

My projects are currently based on Poetry and I have these hooks set-up, and they are just great to keep project in sync, especially since dependabot updates my dependencies on a daily basis.

**Comment by thisiswhereitype** [comment]
`post-checkout` would also be a good stage to run this after

**Comment by BinDruid** [comment]
I second this too.
For projects that frequently change the `uv.lock` file, I've added a post-merge hook to inform developers to run `uv sync` locally.
It would be nice to have this as a built-in post-merge hook.

**Comment by BinDruid** [comment]
@nathanjmcdougall 
@zanieb 

Correct me if wrong but I assume there is no perfect solution for this.
According to pre-commit [documentation](https://pre-commit.com/#post-merge) `post-merge` hooks always run, regardless of which files have changed.

> post-merge hooks do not operate on files so they must be set as always_run: true or they will always be skipped.

Therefore, adding a `post-merge` hook to check if only `uv.lock` or `pyproject.toml` has changed and then running `uv sync` is not possible.

Basically, `uv sync` will always run after each merge, regardless of which files were modified.

With this consideration, a sample hook will look like this:

```yaml    
- id: uv-sync
      name: uv-lock
      description: "Automatically run 'uv sync' after merge or pull"
      entry: uv sync --locked
      language: python
      args: []
      stages: [post-merge]
      always_run: true
      pass_filenames: false
      additional_dependencies: []
      minimum_pre_commit_version: "2.9.2"
```
