### ISSUE TITLE
pip-compile only works if requirements.in exists

### ISSUE THREAD

**Issue by aa89113** [astral-sh/uv-pre-commit#20]
I believe this should work if pyproject.toml exists in repo.

**Comment by salmundani** [comment]
Use the following hook:
```yaml
hooks:
      - id: pip-compile
        args: [pyproject.toml, -o, requirements.txt]
        files: "pyproject.toml"
```
