### ISSUE TITLE
`pip-compile` fails with  `uv run --no-sync pre-commit run --all-files`

### ISSUE THREAD

**Issue by AlmerCarbonEquity** [astral-sh/uv-pre-commit#21]
We use `uv` in our CI (using python 3.13):

```
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Set up virtual environment
        run: uv venv
      - name: Install Python dependencies
        run: uv pip install -r requirements-dev.txt
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Install Node.js globals
        run: npm install globals
      - name: Run pre-commit
        run: uv run --no-sync pre-commit run --show-diff-on-failure --color=always --all-files
```

But this hook is failing, since it makes changes to all 3 `requirements.txt` files:

```
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.4.27
    hooks:
      - id: pip-compile
        name: pip-compile production
        args: [pyproject.toml, -o, requirements.txt, --generate-hashes]
        files: ^pyproject.toml|requirements.txt$
      - id: pip-compile
        name: pip-compile test
        args:
          [
            pyproject.toml,
            -o,
            requirements-test.txt,
            --extra,
            test,
            --generate-hashes,
          ]
        files: ^pyproject.toml|requirements-test.txt$
      - id: pip-compile
        name: pip-compile dev
        args:
          [
            pyproject.toml,
            -o,
            requirements-dev.txt,
            --all-extras,
            --generate-hashes,
          ]
        files: ^pyproject.toml|requirements-dev.txt$
```

I can reproduce the changes locally by not running `uv pip install -r requirements-dev.txt` after making a new venv with `uv venv`, and then running `uv run --no-sync pre-commit run --show-diff-on-failure --color=always --all-files`, which makes me think the hook/pre-commit might not be using the venv.
