### ISSUE TITLE
Hook to sync pre-commit repos with lockfile versions

### ISSUE THREAD

**Issue by gresavage** [astral-sh/uv-pre-commit#23]
An incredibly useful tool I've become accustomed to with Poetry/PDM is the use of a tool/plugin to sync the tagged pre-commit repo versions with the versions of the tools in the lockfile

See: https://github.com/GabDug/sync-pre-commit-lock
See: https://github.com/floatingpurr/sync_with_poetry

This way, whenever a tool version is updated the developer doesn't have to manually update the pre-commit config to keep the versions in-sync, especially sync `pre-commit autoupdate` will only update to the latest repo versions, which might conflict with the actual tool versions pinned by UV 

Possibly related to: https://github.com/astral-sh/uv-pre-commit/issues/17

**Comment by nathanjmcdougall** [comment]
Personally I'm thinking `sync-pre-commit-lock` is the best place for this functionality to live:
https://github.com/GabDug/sync-pre-commit-lock/issues/42

Most of the time, the recommendation is _not_ to install a pre-commit tool in the `venv` as well as as a pre-commit hook. But in some cases, it seems unavoidable, e.g. when wanting to use the ruff VS Code extension - it will look at the venv for a ruff install, otherwise it will default to some random version. So in such a case it really needs to be declared both as a dev dependency and a pre-commit hook - so ideally there would be some syncing logic.

As a workaround, in the interim, I am using the hacky technique of using `uv run` via a system hook. This isn't compatible with the `pre-commit.ci` bot framework though, and presumably there are other disadvantages:

```YAML
-   repo: local
    hooks:
    -   id: ruff-check
        name: ruff-check
        entry: uv run --frozen ruff check --fix
        language: system
        always_run: true
        pass_filenames: false
  ```
