### ISSUE TITLE
`uv==0.5` seems to mess with `uv-lock` `pre-commit` hook

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/uv-pre-commit#25]
I have this in my `pre-commit-config.yaml`:

```yaml
default_language_version:
  python: python3
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: X
    hooks:
      - id: uv-lock
```

When the `rev` is below `0.5`, the `uv-lock` hook passes within a branch.

After `pre-commit autoupdate` to `uv==0.5.1`, the `uv-lock` hook fails within a branch commit-by-commit:

```none
 [[package]]
 name = "my-pkg"
-version = "0.14.3.dev3+ge144e1b"
+version = "0.14.3.dev5+g1ca1866"
```
