### ISSUE TITLE
Add uv-run hook

### ISSUE THREAD

**Issue by danielhollas** [astral-sh/uv-pre-commit#37]
We have a small python script with a handful of external dependencies which we want to run as a local pre-commit hook. To ensure that the dependencies are installed, it would be great to use PEP-723 inline script metadata and use `uv run --script` to execute the script.

Would it be possible to add a `uv-run` hook that would allow for this? 
This would be helpful since we don't want our developer to have to install `uv` (as much as I love it of course :D), so ideally this would "just work" behind the scenes.

I am happy to submit a PR if that would be helpful.

Thanks!

(if there are other ways to do the thing outlined above I am all ears)

**Comment by danielhollas** [comment]
Related to #14

**Comment by danielhollas** [comment]
@zanieb would you be open to this idea?

**Comment by zanieb** [comment]
What would this look like in practice?

**Comment by danielhollas** [comment]
So basically I'd like to change the current local hook (which requires global uv installation) that looks like this in `.pre-commit-config.yaml`

```yaml
  - repo: local
    hooks:
    - id: local-python-script
      name: Standalone script with PEP-723 deps    
      entry: uv run ./utils/standalone_script.py --some-option  
      language: system
      pass_filenames: false
```

to

```yaml
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.22
    hooks:                                                                                                                         
    - id: uv-run
      name: Standalone script with PEP-723 deps
      args: ['utils/standalone_script.py', '--some-option']
```

Because of the way `uv run` works, this would also cover a use case of running a command/script within the virtual environment of the project. The typical use case for this would be running `mypy`, as described in https://github.com/astral-sh/uv-pre-commit/issues/14#issuecomment-2559994840

I am also not a pre-commit expert so it's possible there are some issues that I am not seeing, but it looks doable.
