### ISSUE TITLE
Support workspaces by default

### ISSUE THREAD

**Issue by polothy** [astral-sh/uv-pre-commit#47]
Unsure if this was intentional or not, but I was trying the `uv-lock` hook and thought it wasn't working and it was because of the `files` selector and I was editing a workspace `toml` file. This ended up working:

```yaml
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.14
    hooks:
      - id: uv-lock
        files: ^(uv\.lock|pyproject\.toml|uv\.toml|.*/pyproject\.toml)$
```

The bit I added was `|.*/pyproject\.toml` which may or may not be 100% right but it worked 😄
