### ISSUE TITLE
New hook? uv-update-requirements

### ISSUE THREAD

**Issue by pjrulez** [astral-sh/uv-pre-commit#48]
Why not have a hook that can export old school requirements.txt and update the legacy requirements.txt without interrupting git commit?

I wanted to achieve similar with uv-export hook, but it was not possible to do this.

```
-   repo: local
    hooks:
    - id: update-requirements
      name: Update requirements.txt
      entry: bash -c 'uv pip freeze >> requirements.txt && git add requirements.txt'
      language: system
      types: [file]
      files: \.(json|py|toml)
      stages: [pre-commit]
```

Thought it'd be a legit addition.
