### ISSUE TITLE
uv-pre-commit creates `# via` annotations when `uv export` dosent

### ISSUE THREAD

**Issue by GitToby** [astral-sh/uv-pre-commit#49]
Ive noticed the `uv export` command doesn't produce `# via` annotations, whereas the pre-commmit hook does:

```
# This file was autogenerated by uv via the following command:
#    uv export --no-editable --frozen --no-hashes --output-file=requirements.cli.txt
annotated-types==0.7.0
blinker==1.9.0
certifi==2025.1.31
cfgv==3.4.0
charset-normalizer==3.4.1
...
```

vs 

```
# This file was autogenerated by uv via the following command:
#    uv export --no-editable --frozen --no-hashes --output-file=requirements.pre-commit.txt
annotated-types==0.7.0
    # via pydantic
blinker==1.9.0
    # via flask
certifi==2025.1.31
    # via requests
cfgv==3.4.0
    # via pre-commit
charset-normalizer==3.4.1
    # via requests
...
```

Here are some files to reproduce:

```yaml
# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.14
    hooks:
      - id: uv-lock
      # Note: these will produce the `#via` annotations, whereas raw `uv export` won't.
      - id: uv-export
        args: ["--quiet", "--no-editable", "--frozen", "--no-hashes", "--output-file=requirements.pre-commit.txt"]
```

```toml
# pyproject.toml
[project]
name = "uv-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docx2txt2>=1.0.4",
    "pydantic>=2.11.3",
    "requests>=2.32.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
```

its not a massive issue, but curious why were having pip-compile type annotations on the export call. I cant see where in the config the flag would even be set for these `# via` annotations to be applied for `uv export` or even in this repo. 

relevant issue? https://github.com/astral-sh/uv/issues/7159

To reproduce:
- new git repo
- copy files above to the relevant locations
- `uv sync`
- `uv run pre-commit install`
- `git add * && git commit -m "init"`
- `uv run pre-commit --all-files`
- look at `requirements.pre-commit.txt`
- run the command in the header and watch file change.
